(()=>{
'use strict';
const $=s=>document.querySelector(s);const canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false});
const ui={loading:$('#loading'),start:$('#start'),pause:$('#pauseModal'),win:$('#win'),settings:$('#settingsModal'),level:$('#level'),subtitle:$('#subtitle'),world:$('#world'),bar:$('#bar'),timer:$('#timer'),streak:$('#streak'),score:$('#score'),coins:$('#coins'),stars:$('#stars'),hints:$('#hints'),list:$('#wordList'),toast:$('#toast'),combo:$('#combo')};
const LEVELS=[
{world:'NEXO NEÓN',title:'Primer contacto',size:8,words:['NUBE','LUZ','RAYO','LUNA','NOVA','ASTRO'],colors:['#173351','#35e7ff','#8e62ff']},
{world:'NEXO NEÓN',title:'Circuito oculto',size:8,words:['PIXEL','ROBOT','DATOS','CHIP','CLAVE','RED'],colors:['#182b4c','#31d9ff','#745cff']},
{world:'JARDÍN ORBITAL',title:'Vida estelar',size:9,words:['FLORA','HOJA','RAIZ','BROTE','SEMILLA','VERDE'],colors:['#153d35','#5dffb0','#8e62ff']},
{world:'JARDÍN ORBITAL',title:'Ecos del bosque',size:9,words:['CEDRO','PINO','HONGO','MUSGO','RAMA','BOSQUE'],colors:['#173b31','#64f4a8','#4fcf7c']},
{world:'ABISMO AZUL',title:'Bajo la marea',size:10,words:['CORAL','DELFIN','PERLA','OCEANO','TIBURON','MAREA'],colors:['#103852','#41c8ff','#4e73ff']},
{world:'ABISMO AZUL',title:'Ciudad sumergida',size:10,words:['TRITON','ANCLA','TESORO','BARCO','ARENA','ISLA'],colors:['#0d3652','#33bdf2','#4973ff']},
{world:'TEMPLO SOLAR',title:'Símbolos antiguos',size:10,words:['TEMPLO','FARAON','ORO','DUNA','ESFINGE','NILO'],colors:['#503512','#ffc45d','#ff7d4d']},
{world:'TEMPLO SOLAR',title:'La cámara secreta',size:11,words:['PIRAMIDE','JEROGLIFO','MOMIA','SARCOFAGO','REINA','SOL'],colors:['#49300f','#ffd06a','#ff734d']},
{world:'VACÍO CÓSMICO',title:'Constelación',size:11,words:['GALAXIA','COMETA','PLANETA','ORBITA','COSMOS','METEORO'],colors:['#251943','#bf68ff','#45d7ff']},
{world:'VACÍO CÓSMICO',title:'Horizonte final',size:12,words:['UNIVERSO','GRAVEDAD','NEBULOSA','ESTRELLA','SATELITE','ECLIPSE'],colors:['#241640','#b55cff','#35cfff']},
{world:'CÓDIGO MAESTRO',title:'Mente digital',size:12,words:['ALGORITMO','SISTEMA','CODIGO','MATRIZ','VECTOR','MEMORIA'],colors:['#17304b','#35e7ff','#8e62ff']},
{world:'CÓDIGO MAESTRO',title:'Núcleo supremo',size:13,words:['INTELIGENCIA','PROGRAMA','SERVIDOR','INTERFAZ','DIGITAL','FUTURO'],colors:['#192b4e','#31d9ff','#a05cff']}
];
const dirs=[[0,1],[1,0],[1,1],[1,-1],[0,-1],[-1,0],[-1,-1],[-1,1]],letters='ABCDEFGHIJKLMNÑOPQRSTUVWXYZ';
let save=load(),levelIndex=save.level||0,grid=[],placed=[],found=new Set(),cells=[],selected=[],startCell=null,dragging=false,paused=true,elapsed=0,score=0,streak=0,hints=3,rotation=0,targetRotation=0,particles=[],stars=[];let dpr=1,W=0,H=0,last=performance.now(),audio=null;
function load(){try{return JSON.parse(localStorage.getItem('wq3d-v21'))||{coins:120,stars:0,level:0,completed:{},sound:true,vibration:true,quality:'high'}}catch{return{coins:120,stars:0,level:0,completed:{},sound:true,vibration:true,quality:'high'}}}
function persist(){localStorage.setItem('wq3d-v21',JSON.stringify(save))}
function fmt(v){const s=Math.floor(v),m=Math.floor(s/60);return String(m).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function normalize(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
function rand(n){return Math.floor(Math.random()*n)}
function generate(level){const n=level.size,g=Array.from({length:n},()=>Array(n).fill('')),out=[];for(const raw of level.words){const word=normalize(raw);let ok=false;for(let tries=0;tries<350&&!ok;tries++){const [dr,dc]=dirs[rand(dirs.length)],r=rand(n),c=rand(n),er=r+dr*(word.length-1),ec=c+dc*(word.length-1);if(er<0||ec<0||er>=n||ec>=n)continue;let valid=true;for(let i=0;i<word.length;i++){const v=g[r+dr*i][c+dc*i];if(v&&v!==word[i]){valid=false;break}}if(!valid)continue;const path=[];for(let i=0;i<word.length;i++){g[r+dr*i][c+dc*i]=word[i];path.push({r:r+dr*i,c:c+dc*i})}out.push({raw,word,path});ok=true}if(!ok)return generate({...level,size:n+1})}for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(!g[r][c])g[r][c]=letters[rand(letters.length)];return{grid:g,placed:out,size:n}}
function resize(){dpr=Math.min(devicePixelRatio||1,save.quality==='high'?2:1.35);W=innerWidth;H=innerHeight;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
function build(){const result=generate(LEVELS[levelIndex]);grid=result.grid;placed=result.placed;found.clear();selected=[];score=0;streak=0;elapsed=0;hints=3;rotation=targetRotation=0;renderList();updateHud();layoutCells()}
function layoutCells(){const n=grid.length;const mobile=W<820;const top=mobile?220:120;const bottom=mobile?250:100;const availW=mobile?W-28:W-620;const availH=H-top-bottom;const board=Math.max(220,Math.min(availW,availH*1.05,720));const gap=Math.max(2,board/n*.07);const size=(board-gap*(n-1))/n;const cx=mobile?W/2:W/2,cy=top+availH/2+20;cells=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++)cells.push({r,c,size,gap,cx,cy,lift:0,target:0,state:'idle',pulse:Math.random()*6.28})}
function project(cell){const n=grid.length;const s=cell.size+cell.gap;let x=(cell.c-(n-1)/2)*s,y=(cell.r-(n-1)/2)*s;const cos=Math.cos(rotation),sin=Math.sin(rotation);const rx=x*cos-y*sin,ry=x*sin+y*cos;const isoX=cell.cx+rx,isoY=cell.cy+ry*.72-rx*.12-cell.lift;return{x:isoX,y:isoY}}
function drawBackground(t){const lev=LEVELS[levelIndex],g=ctx.createRadialGradient(W*.5,H*.38,20,W*.5,H*.4,Math.max(W,H)*.75);g.addColorStop(0,lev.colors[0]);g.addColorStop(.5,'#07101f');g.addColorStop(1,'#030711');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.35;for(const s of stars){s.y+=s.v;if(s.y>H){s.y=-4;s.x=Math.random()*W}ctx.fillStyle=s.c;ctx.fillRect(s.x,s.y,s.r,s.r)}ctx.globalAlpha=1;const glow=ctx.createRadialGradient(W*.5,H*.55,0,W*.5,H*.55,Math.min(W,H)*.55);glow.addColorStop(0,lev.colors[1]+'24');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H)}
function shade(hex,p){const n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)+p)),g=Math.max(0,Math.min(255,((n>>8)&255)+p)),b=Math.max(0,Math.min(255,(n&255)+p));return`rgb(${r},${g},${b})`}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawCell(cell,t){const p=project(cell),s=cell.size,depth=Math.max(5,s*.16),lev=LEVELS[levelIndex];let base=lev.colors[0],edge=lev.colors[1];if(cell.state==='preview'){base=lev.colors[1];edge='#ffffff'}if(cell.state==='found'){base='#1c745e';edge='#5dffb0'}const x=p.x-s/2,y=p.y-s/2;ctx.save();ctx.shadowBlur=cell.state==='idle'?8:22;ctx.shadowColor=edge;ctx.globalAlpha=.42;ctx.fillStyle=shade(base,-18);ctx.beginPath();ctx.moveTo(x,y+s);ctx.lineTo(x+depth,y+s+depth);ctx.lineTo(x+s+depth,y+s+depth);ctx.lineTo(x+s,y+s);ctx.closePath();ctx.fill();ctx.fillStyle=shade(base,-28);ctx.beginPath();ctx.moveTo(x+s,y);ctx.lineTo(x+s+depth,y+depth);ctx.lineTo(x+s+depth,y+s+depth);ctx.lineTo(x+s,y+s);ctx.closePath();ctx.fill();ctx.globalAlpha=1;const grad=ctx.createLinearGradient(x,y,x+s,y+s);grad.addColorStop(0,shade(base,18));grad.addColorStop(1,shade(base,-4));ctx.fillStyle=grad;roundRect(x,y,s,s,Math.max(5,s*.13));ctx.fill();ctx.lineWidth=Math.max(1,cell.state==='idle'?1.2:2.2);ctx.strokeStyle=edge;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#f5fbff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`800 ${Math.max(13,s*.42)}px system-ui`;ctx.fillText(grid[cell.r][cell.c],p.x,p.y+1);ctx.restore();cell.hit={x:x-2,y:y-2,w:s+depth+4,h:s+depth+4,cx:p.x,cy:p.y}}
function drawBoard(t){const sorted=[...cells].sort((a,b)=>project(a).y-project(b).y);for(const c of sorted){c.lift+=(c.target-c.lift)*.18;if(c.state==='found')c.target=7+Math.sin(t*.004+c.pulse)*1.5;drawCell(c,t)}}
function drawParticles(){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vy+=.035;p.life-=.018;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();if(p.life<=0)particles.splice(i,1)}ctx.globalAlpha=1}
function animate(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!paused)elapsed+=dt;rotation+=(targetRotation-rotation)*.1;drawBackground(now);drawBoard(now);drawParticles();ui.timer.textContent=fmt(elapsed);requestAnimationFrame(animate)}
function renderList(){ui.list.innerHTML='';for(const p of placed){const el=document.createElement('div');el.className='word';el.dataset.word=p.word;el.innerHTML=`<span>${p.raw}</span><b>✓</b>`;ui.list.appendChild(el)}}
function updateHud(){const l=LEVELS[levelIndex];ui.level.textContent='Nivel '+(levelIndex+1);ui.subtitle.textContent=l.title;ui.world.textContent='MUNDO '+(Math.min(5,Math.floor(levelIndex/2)+1))+' · '+l.world;ui.score.textContent=score;ui.streak.textContent=streak;ui.coins.textContent=save.coins;ui.stars.textContent=save.stars;ui.hints.textContent=hints;ui.bar.style.width=(found.size/placed.length*100)+'%'}
function getPoint(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function hit(e){const p=getPoint(e);let best=null,dist=1e9;for(const c of cells){if(!c.hit)continue;if(p.x>=c.hit.x&&p.x<=c.hit.x+c.hit.w&&p.y>=c.hit.y&&p.y<=c.hit.y+c.hit.h){const d=Math.hypot(p.x-c.hit.cx,p.y-c.hit.cy);if(d<dist){dist=d;best=c}}}return best}
function path(a,b){const dr=b.r-a.r,dc=b.c-a.c;if(!(dr===0||dc===0||Math.abs(dr)===Math.abs(dc)))return[a];const sr=Math.sign(dr),sc=Math.sign(dc),len=Math.max(Math.abs(dr),Math.abs(dc)),out=[];for(let i=0;i<=len;i++){const c=cells.find(x=>x.r===a.r+sr*i&&x.c===a.c+sc*i);if(c)out.push(c)}return out}
function clearPreview(){for(const c of cells)if(c.state==='preview'){c.state='idle';c.target=0}}
function preview(hitCell){clearPreview();selected=path(startCell,hitCell);for(const c of selected)if(c.state!=='found'){c.state='preview';c.target=8}}
function validate(){if(selected.length<2){clearPreview();return}const word=selected.map(c=>grid[c.r][c.c]).join(''),rev=[...word].reverse().join(''),match=placed.find(p=>!found.has(p.word)&&(p.word===word||p.word===rev));if(match){found.add(match.word);for(const c of selected){c.state='found';c.target=7}ui.list.querySelector(`[data-word="${match.word}"]`)?.classList.add('found');streak++;score+=match.word.length*100+streak*25;save.coins+=5;burst(selected[Math.floor(selected.length/2)]);sound(660,.08);setTimeout(()=>sound(880,.1),75);if(save.vibration&&navigator.vibrate)navigator.vibrate([25,20,35]);showCombo(streak);persist();updateHud();if(found.size===placed.length)setTimeout(winLevel,700)}else{streak=0;clearPreview();sound(150,.1);toast('Esa combinación no está en la lista');updateHud()}}
function burst(cell){const p=project(cell),lev=LEVELS[levelIndex],count=save.quality==='low'?18:42;for(let i=0;i<count;i++)particles.push({x:p.x,y:p.y,vx:(Math.random()-.5)*5,vy:(Math.random()-.8)*5,r:Math.random()*3+1,life:1,color:i%2?lev.colors[1]:lev.colors[2]})}
function sound(freq,dur=.08){if(!save.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='triangle';g.gain.setValueAtTime(.04,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch{}}
function toast(t){ui.toast.textContent=t;ui.toast.classList.remove('show');void ui.toast.offsetWidth;ui.toast.classList.add('show')}
function showCombo(n){ui.combo.textContent=n>=4?'RACHA x'+n:n===3?'¡INCREÍBLE!':n===2?'¡GENIAL!':'¡ENCONTRADA!';ui.combo.classList.remove('show');void ui.combo.offsetWidth;ui.combo.classList.add('show')}
function start(i=levelIndex){levelIndex=Math.max(0,Math.min(i,LEVELS.length-1));paused=false;ui.start.classList.remove('visible');ui.pause.classList.remove('visible');ui.win.classList.remove('visible');build();toast('Nivel '+(levelIndex+1)+': '+LEVELS[levelIndex].title)}
function winLevel(){paused=true;const target=55+levelIndex*13,earned=elapsed<=target?3:elapsed<=target*1.6?2:1,reward=20+earned*10;save.coins+=reward;save.stars+=earned;save.completed[levelIndex]={stars:earned,score,time:elapsed};save.level=Math.min(levelIndex+1,LEVELS.length-1);persist();$('#winStars').textContent='★'.repeat(earned)+'☆'.repeat(3-earned);$('#finalScore').textContent=score;$('#finalTime').textContent=fmt(elapsed);$('#finalCoins').textContent='+'+reward;$('#winTitle').textContent=earned===3?'¡Dominio absoluto!':'¡Misión completada!';$('#winText').textContent=`Encontraste ${placed.length} palabras en ${fmt(elapsed)}.`;ui.win.classList.add('visible');sound(523,.15);setTimeout(()=>sound(659,.15),150);setTimeout(()=>sound(784,.2),300)}
function hint(){if(paused||hints<=0)return;const p=placed.find(x=>!found.has(x.word));if(!p)return;hints--;save.coins=Math.max(0,save.coins-10);const first=cells.find(c=>c.r===p.path[0].r&&c.c===p.path[0].c);first.state='preview';first.target=12;setTimeout(()=>{if(first.state==='preview'){first.state='idle';first.target=0}},1300);toast('La palabra '+p.raw+' empieza aquí');persist();updateHud()}
canvas.addEventListener('pointerdown',e=>{if(paused)return;const c=hit(e);if(!c)return;dragging=true;startCell=c;canvas.setPointerCapture?.(e.pointerId);preview(c);sound(320,.03)});canvas.addEventListener('pointermove',e=>{if(dragging&&!paused){const c=hit(e);if(c)preview(c)}});const end=()=>{if(!dragging)return;dragging=false;validate();startCell=null;selected=[]};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
$('#play').onclick=()=>start(save.level||0);$('#pause').onclick=()=>{if(!paused){paused=true;ui.pause.classList.add('visible')}};$('#resume').onclick=()=>{paused=false;ui.pause.classList.remove('visible');last=performance.now()};$('#restart').onclick=()=>start(levelIndex);$('#replay').onclick=()=>start(levelIndex);$('#next').onclick=()=>start((levelIndex+1)%LEVELS.length);$('#hint').onclick=hint;$('#left').onclick=()=>targetRotation-=Math.PI/8;$('#right').onclick=()=>targetRotation+=Math.PI/8;$('#center').onclick=()=>targetRotation=0;$('#home').onclick=()=>{paused=true;ui.start.classList.add('visible')};$('#settings').onclick=()=>{paused=true;ui.settings.classList.add('visible')};$('#closeSettings').onclick=()=>{ui.settings.classList.remove('visible');if(!ui.start.classList.contains('visible')&&!ui.win.classList.contains('visible'))paused=false};
$('#sound').checked=save.sound;$('#vibration').checked=save.vibration;$('#quality').value=save.quality;$('#sound').onchange=e=>{save.sound=e.target.checked;persist()};$('#vibration').onchange=e=>{save.vibration=e.target.checked;persist()};$('#quality').onchange=e=>{save.quality=e.target.value;persist();resize();layoutCells();toast('Calidad aplicada')};$('#reset').onclick=()=>{if(confirm('¿Restablecer todo el progreso?')){localStorage.removeItem('wq3d-v21');location.reload()}};
addEventListener('resize',()=>{resize();layoutCells()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused){paused=true;ui.pause.classList.add('visible')}});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
function boot(){resize();stars=Array.from({length:save.quality==='low'?45:100},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.8+.4,v:Math.random()*.18+.03,c:Math.random()>.75?'#35e7ff':'#ffffff'}));build();requestAnimationFrame(animate);setTimeout(()=>ui.loading.classList.add('hide'),450);setTimeout(()=>ui.loading.remove(),1000)}
try{boot()}catch(err){console.error(err);ui.loading.innerHTML='<b>No se pudo iniciar el juego</b><small>Recarga la página para intentarlo otra vez.</small>';}
})();
