'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const ui={canvas:$('#gl'),labels:$('#labels'),particles:$('#particles'),loading:$('#loading'),loadingText:$('#loadingText'),error:$('#error'),errorText:$('#errorText'),start:$('#start'),pause:$('#pauseScreen'),win:$('#win'),settings:$('#settingsScreen'),stars:$('#stars'),coins:$('#coins'),world:$('#world'),title:$('#title'),subtitle:$('#subtitle'),levelBadge:$('#levelBadge'),bar:$('#bar'),progressText:$('#progressText'),time:$('#time'),score:$('#score'),hints:$('#hints'),wordList:$('#wordList'),toast:$('#toast'),combo:$('#combo')};
const LEVELS=[
 {w:'NEXO NEÓN',t:'Primer contacto',n:8,a:['NUBE','LUZ','RAYO','LUNA','NOVA','ASTRO'],c:[0.10,0.72,0.92]},
 {w:'NEXO NEÓN',t:'Circuito oculto',n:8,a:['PIXEL','ROBOT','DATOS','CHIP','CLAVE','RED'],c:[0.10,0.72,0.92]},
 {w:'JARDÍN ORBITAL',t:'Vida estelar',n:9,a:['FLORA','HOJA','RAIZ','BROTE','SEMILLA','VERDE'],c:[0.18,0.86,0.58]},
 {w:'JARDÍN ORBITAL',t:'Ecos del bosque',n:9,a:['CEDRO','PINO','HONGO','MUSGO','RAMA','BOSQUE'],c:[0.18,0.86,0.58]},
 {w:'ABISMO AZUL',t:'Bajo la marea',n:10,a:['CORAL','DELFIN','PERLA','OCEANO','TIBURON','MAREA'],c:[0.08,0.52,0.96]},
 {w:'ABISMO AZUL',t:'Ciudad sumergida',n:10,a:['TRITON','ANCLA','TESORO','BARCO','ARENA','ISLA'],c:[0.08,0.52,0.96]},
 {w:'TEMPLO SOLAR',t:'Símbolos antiguos',n:10,a:['TEMPLO','FARAON','ORO','DUNA','ESFINGE','NILO'],c:[1.0,0.58,0.16]},
 {w:'TEMPLO SOLAR',t:'La cámara secreta',n:10,a:['PIRAMIDE','MOMIA','SARCOFAGO','REINA','SOL','ORO'],c:[1.0,0.58,0.16]},
 {w:'VACÍO CÓSMICO',t:'Constelación',n:10,a:['GALAXIA','COMETA','PLANETA','ORBITA','COSMOS','METEORO'],c:[0.64,0.30,1.0]},
 {w:'VACÍO CÓSMICO',t:'Horizonte final',n:10,a:['UNIVERSO','GRAVEDAD','NEBULOSA','ESTRELLA','SATELITE','ECLIPSE'],c:[0.64,0.30,1.0]},
 {w:'CÓDIGO MAESTRO',t:'Mente digital',n:10,a:['ALGORITMO','SISTEMA','CODIGO','MATRIZ','VECTOR','MEMORIA'],c:[0.15,0.88,0.95]},
 {w:'CÓDIGO MAESTRO',t:'Núcleo supremo',n:10,a:['PROGRAMA','SERVIDOR','INTERFAZ','DIGITAL','FUTURO','NODOS'],c:[0.15,0.88,0.95]}
];
const DEF={coins:100,stars:0,level:0,completed:{},sound:true,vibration:true,quality:'high'};
let save=(()=>{try{return {...DEF,...JSON.parse(localStorage.getItem('wq3-native'))}}catch{return {...DEF}}})();
const persist=()=>localStorage.setItem('wq3-native',JSON.stringify(save));
let gl,program,bufPos,bufNorm,uMVP,uModel,uColor,uLight,uSelected,uTime,grid=[],placements=[],cells=[],labelEls=[],found=new Set(),selection=[],selecting=false,startCell=null,current=save.level||0,elapsed=0,points=0,streak=0,hints=3,paused=true,last=0,yaw=0,targetYaw=0,viewProj=new Float32Array(16),boardModel=new Float32Array(16),audioCtx;
const DPR=()=>Math.min(devicePixelRatio||1,save.quality==='high'?2:save.quality==='medium'?1.45:1);

function m4(){return new Float32Array(16)}
function identity(o){o.set([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);return o}
function multiply(o,a,b){const r=m4();for(let c=0;c<4;c++)for(let rI=0;rI<4;rI++)r[c*4+rI]=a[0*4+rI]*b[c*4+0]+a[1*4+rI]*b[c*4+1]+a[2*4+rI]*b[c*4+2]+a[3*4+rI]*b[c*4+3];o.set(r);return o}
function perspective(o,fovy,aspect,near,far){const f=1/Math.tan(fovy/2),nf=1/(near-far);o.set([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);return o}
function lookAt(o,e,c,u){let zx=e[0]-c[0],zy=e[1]-c[1],zz=e[2]-c[2],l=Math.hypot(zx,zy,zz)||1;zx/=l;zy/=l;zz/=l;let xx=u[1]*zz-u[2]*zy,xy=u[2]*zx-u[0]*zz,xz=u[0]*zy-u[1]*zx;l=Math.hypot(xx,xy,xz)||1;xx/=l;xy/=l;xz/=l;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;o.set([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-(xx*e[0]+xy*e[1]+xz*e[2]),-(yx*e[0]+yy*e[1]+yz*e[2]),-(zx*e[0]+zy*e[1]+zz*e[2]),1]);return o}
function translateScaleYRot(o,x,y,z,s,ry){const c=Math.cos(ry),q=Math.sin(ry);o.set([c*s,0,-q*s,0,0,s,0,0,q*s,0,c*s,0,x,y,z,1]);return o}
function project(x,y,z,m){const w=m[3]*x+m[7]*y+m[11]*z+m[15],nx=(m[0]*x+m[4]*y+m[8]*z+m[12])/w,ny=(m[1]*x+m[5]*y+m[9]*z+m[13])/w,nz=(m[2]*x+m[6]*y+m[10]*z+m[14])/w;return {x:(nx*.5+.5)*innerWidth,y:(1-(ny*.5+.5))*innerHeight,z:nz,w}}
function norm(w){return w.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
function fmt(t){return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`}
function beep(f=600,d=.07){if(!save.sound)return;try{audioCtx ||= new (AudioContext||webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.type='triangle';g.gain.value=.045;g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}
function toast(t){ui.toast.textContent=t;ui.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('show'),1400)}
function vibrate(p=25){if(save.vibration&&navigator.vibrate)navigator.vibrate(p)}
function burst(x=innerWidth/2,y=innerHeight/2,color='#46e8ff'){if(!ui.particles)return;for(let i=0;i<18;i++){const p=document.createElement('i');p.className='particle';p.style.left=x+'px';p.style.top=y+'px';p.style.background=color;p.style.color=color;const a=Math.random()*Math.PI*2,d=45+Math.random()*95;p.style.setProperty('--dx',Math.cos(a)*d+'px');p.style.setProperty('--dy',Math.sin(a)*d+'px');ui.particles.appendChild(p);setTimeout(()=>p.remove(),800)}}

function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}
function initGL(){gl=ui.canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'high-performance'})||ui.canvas.getContext('experimental-webgl');if(!gl)throw new Error('WebGL no está disponible en este navegador.');const vs=`attribute vec3 p;attribute vec3 n;uniform mat4 mvp;uniform mat4 model;varying vec3 vn;varying vec3 wp;void main(){vec4 w=model*vec4(p,1.0);wp=w.xyz;vn=mat3(model)*n;gl_Position=mvp*vec4(p,1.0);}`;const fs=`precision mediump float;varying vec3 vn;varying vec3 wp;uniform vec3 color;uniform vec3 light;uniform float selected;uniform float time;void main(){vec3 N=normalize(vn);vec3 L=normalize(light);float diffuse=max(dot(N,L),0.0);float hemi=N.y*0.5+0.5;float rim=pow(1.0-max(dot(N,normalize(vec3(0.0,0.7,1.0))),0.0),2.4);float top=pow(max(N.y,0.0),3.0);vec3 c=color*(0.22+diffuse*0.62+hemi*0.20);c+=vec3(0.08,0.18,0.30)*rim+c*top*0.28;c+=selected*vec3(0.18,0.78,0.96)*(0.72+0.28*sin(time*5.5));float edge=0.025*sin(wp.x*5.0+wp.z*4.0+time*0.6);c+=edge;gl_FragColor=vec4(c,1.0);}`;program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));gl.useProgram(program);uMVP=gl.getUniformLocation(program,'mvp');uModel=gl.getUniformLocation(program,'model');uColor=gl.getUniformLocation(program,'color');uLight=gl.getUniformLocation(program,'light');uSelected=gl.getUniformLocation(program,'selected');uTime=gl.getUniformLocation(program,'time');
 const P=[-1,-1,1,1,-1,1,1,1,1,-1,-1,1,1,1,1,-1,1,1, 1,-1,-1,-1,-1,-1,-1,1,-1,1,-1,-1,-1,1,-1,1,1,-1, -1,1,1,1,1,1,1,1,-1,-1,1,1,1,1,-1,-1,1,-1, -1,-1,-1,1,-1,-1,1,-1,1,-1,-1,-1,1,-1,1,-1,-1,1, 1,-1,1,1,-1,-1,1,1,-1,1,-1,1,1,1,-1,1,1,1, -1,-1,-1,-1,-1,1,-1,1,1,-1,-1,-1,-1,1,1,-1,1,-1].map(v=>v*.42);
 const N=[];[[0,0,1],[0,0,-1],[0,1,0],[0,-1,0],[1,0,0],[-1,0,0]].forEach(n=>{for(let i=0;i<6;i++)N.push(...n)});bufPos=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,bufPos);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(P),gl.STATIC_DRAW);const ap=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(ap);gl.vertexAttribPointer(ap,3,gl.FLOAT,false,0,0);bufNorm=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,bufNorm);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(N),gl.STATIC_DRAW);const an=gl.getAttribLocation(program,'n');gl.enableVertexAttribArray(an);gl.vertexAttribPointer(an,3,gl.FLOAT,false,0,0);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.uniform3f(uLight,.35,.85,.55);resize();addEventListener('resize',resize)}
function resize(){const d=DPR(),w=Math.max(1,Math.floor(innerWidth*d)),h=Math.max(1,Math.floor(innerHeight*d));if(ui.canvas.width!==w||ui.canvas.height!==h){ui.canvas.width=w;ui.canvas.height=h}gl&&gl.viewport(0,0,w,h)}
function generate(L){const n=L.n,A='ABCDEFGHIJKLMNÑOPQRSTUVWXYZ';grid=Array.from({length:n},()=>Array(n).fill(''));placements=[];const dirs=[[0,1],[1,0],[1,1],[1,-1],[0,-1],[-1,0],[-1,-1],[-1,1]];for(const raw of L.a){const word=norm(raw);let ok=false;for(let q=0;q<900&&!ok;q++){const [dr,dc]=dirs[Math.floor(Math.random()*dirs.length)],r=Math.floor(Math.random()*n),c=Math.floor(Math.random()*n),er=r+dr*(word.length-1),ec=c+dc*(word.length-1);if(er<0||ec<0||er>=n||ec>=n)continue;let good=true;for(let i=0;i<word.length;i++){const v=grid[r+dr*i][c+dc*i];if(v&&v!==word[i]){good=false;break}}if(!good)continue;const list=[];for(let i=0;i<word.length;i++){grid[r+dr*i][c+dc*i]=word[i];list.push({r:r+dr*i,c:c+dc*i})}placements.push({word,raw,cells:list});ok=true}}for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(!grid[r][c])grid[r][c]=A[Math.floor(Math.random()*A.length)]}
function build(){const L=LEVELS[current];generate(L);found.clear();selection=[];elapsed=0;points=0;streak=0;hints=3;cells=[];ui.labels.innerHTML='';labelEls=[];const gap=L.n>=10?.91:1.02,half=(L.n-1)*gap/2;for(let r=0;r<L.n;r++)for(let c=0;c<L.n;c++){const cell={r,c,x:c*gap-half,z:r*gap-half,y:0,targetY:0,scale:1,targetScale:1,found:false,selected:false,letter:grid[r][c],screen:{x:0,y:0,z:0}};cells.push(cell);const el=document.createElement('div');el.className='letter';el.textContent=cell.letter;ui.labels.appendChild(el);labelEls.push(el)}ui.world.textContent=`MUNDO ${Math.floor(current/2)+1} · ${L.w}`;ui.title.textContent=`Nivel ${current+1}`;ui.subtitle.textContent=L.t;ui.levelBadge.textContent=current+1;renderWords();updateHUD()}
function renderWords(){ui.wordList.innerHTML=placements.map(p=>`<div class="word ${found.has(p.word)?'found':''}" data-word="${p.word}">${p.raw}</div>`).join('')}
function updateHUD(){ui.stars.textContent=save.stars;ui.coins.textContent=save.coins;ui.score.textContent=points;ui.hints.textContent=hints;ui.progressText.textContent=`${found.size} / ${placements.length}`;ui.bar.style.width=`${placements.length?found.size/placements.length*100:0}%`;ui.time.textContent=fmt(elapsed)}
function matrices(){const L=LEVELS[current],mobile=innerWidth<760,dist=(mobile?L.n*1.25:L.n*.95)+5.5,eye=[Math.sin(yaw)*dist,mobile?9.5:8.2,Math.cos(yaw)*dist],v=m4(),p=m4();lookAt(v,eye,[0,0,0],[0,1,0]);perspective(p,Math.PI/4,innerWidth/innerHeight,.1,100);multiply(viewProj,p,v)}
function draw(t){if(!gl)return;resize();matrices();const L=LEVELS[current];const bg=[L.c[0]*.018+.006,L.c[1]*.022+.012,L.c[2]*.028+.025];gl.clearColor(bg[0],bg[1],bg[2],1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.uniform1f(uTime,t*.001);for(let i=0;i<cells.length;i++){const c=cells[i];c.y+=(c.targetY-c.y)*.18;c.scale+=(c.targetScale-c.scale)*.18;translateScaleYRot(boardModel,c.x,c.y,c.z,c.scale,0);const mvp=m4();multiply(mvp,viewProj,boardModel);gl.uniformMatrix4fv(uModel,false,boardModel);gl.uniformMatrix4fv(uMVP,false,mvp);let col=c.found?[.08,.82,.50]:c.selected?[Math.min(1,L.c[0]*1.12+.04),Math.min(1,L.c[1]*1.12+.04),Math.min(1,L.c[2]*1.12+.04)]:[.055+L.c[0]*.035,.11+L.c[1]*.04,.20+L.c[2]*.055];gl.uniform3fv(uColor,col);gl.uniform1f(uSelected,c.selected?1:c.found?.35:0);gl.drawArrays(gl.TRIANGLES,0,36);const s=project(c.x,c.y+.47,c.z,viewProj);c.screen=s;const el=labelEls[i];el.style.left=s.x+'px';el.style.top=s.y+'px';el.style.opacity=(s.z>-1&&s.z<1&&s.w>0)?'1':'0';el.style.transform=`translate(-50%,-50%) scale(${Math.max(.72,Math.min(1.18,11/s.w))})`;el.style.color=c.found?'#75ffc1':'#f7fbff'} }
let renderFailed=false;
function loop(t){requestAnimationFrame(loop);if(renderFailed)return;try{if(!last)last=t;const dt=Math.min((t-last)/1000,.05);last=t;if(!paused){elapsed+=dt;ui.time.textContent=fmt(elapsed)}yaw+=(targetYaw-yaw)*.09;draw(t)}catch(err){renderFailed=true;console.error('Error de render:',err);ui.errorText.textContent='Error de render 3D: '+(err.message||String(err));ui.error.classList.add('show')}}
function nearest(x,y){let best=null,d=1e9;for(const c of cells){const q=Math.hypot(c.screen.x-x,c.screen.y-y);if(q<d){d=q;best=c}}return d<Math.max(25,innerWidth/LEVELS[current].n*.48)?best:null}
function lineCells(a,b){const dr=b.r-a.r,dc=b.c-a.c;if(!(dr===0||dc===0||Math.abs(dr)===Math.abs(dc)))return [a];const len=Math.max(Math.abs(dr),Math.abs(dc)),sr=Math.sign(dr),sc=Math.sign(dc),out=[];for(let i=0;i<=len;i++){const c=cells.find(x=>x.r===a.r+sr*i&&x.c===a.c+sc*i);if(c)out.push(c)}return out}
function setSelection(list){cells.forEach(c=>{c.selected=false;if(!c.found){c.targetY=0;c.targetScale=1}});selection=list;list.forEach(c=>{c.selected=true;c.targetY=.18;c.targetScale=1.08})}
function pointerDown(e){if(paused)return;const c=nearest(e.clientX,e.clientY);if(!c)return;selecting=true;startCell=c;ui.canvas.setPointerCapture?.(e.pointerId);setSelection([c]);beep(420,.035);e.preventDefault()}
function pointerMove(e){if(!selecting)return;const c=nearest(e.clientX,e.clientY);if(c)setSelection(lineCells(startCell,c));e.preventDefault()}
function pointerUp(e){if(!selecting)return;selecting=false;const L=LEVELS[current];const word=selection.map(c=>c.letter).join(''),rev=[...word].reverse().join(''),p=placements.find(x=>!found.has(x.word)&&(x.word===word||x.word===rev));if(p){found.add(p.word);selection.forEach(c=>{c.found=true;c.selected=false;c.targetY=.10;c.targetScale=1});points+=100+streak*25;streak++;beep(760,.09);vibrate([18,30,18]);ui.combo.textContent=streak>2?`¡COMBO x${streak}!`:'¡PALABRA!';ui.combo.classList.remove('show');void ui.combo.offsetWidth;ui.combo.classList.add('show');const mid=selection[Math.floor(selection.length/2)]||selection[0];if(mid)burst(mid.screen.x,mid.screen.y,`rgb(${Math.floor(L.c[0]*255)},${Math.floor(L.c[1]*255)},${Math.floor(L.c[2]*255)})`);renderWords();updateHUD();if(found.size===placements.length)setTimeout(win,650)}else{streak=0;selection.forEach(c=>{c.selected=false;if(!c.found){c.targetY=0;c.targetScale=1}});beep(220,.05)}selection=[];e.preventDefault()}
function hint(){if(paused||hints<=0)return;const p=placements.find(x=>!found.has(x.word));if(!p)return;hints--;p.cells.slice(0,Math.min(2,p.cells.length)).forEach(({r,c})=>{const x=cells.find(q=>q.r===r&&q.c===c);x.selected=true;x.targetY=.28;x.targetScale=1.13;setTimeout(()=>{if(!x.found){x.selected=false;x.targetY=0;x.targetScale=1}},1500)});updateHUD();toast(`La palabra empieza con ${p.word[0]}`);beep(900,.08)}
function win(){paused=true;const stars=elapsed<70?3:elapsed<130?2:1,reward=20+stars*10;save.stars+=stars;save.coins+=reward;save.completed[current]=Math.max(save.completed[current]||0,stars);save.level=Math.min(LEVELS.length-1,current+1);persist();$('#winStars').textContent='★ '.repeat(stars)+'☆ '.repeat(3-stars);$('#winTitle').textContent=stars===3?'¡Dominio tridimensional!':'¡Nivel completado!';$('#winText').textContent=`Encontraste ${placements.length} palabras en ${fmt(elapsed)}.`;$('#finalScore').textContent=points;$('#finalTime').textContent=fmt(elapsed);$('#reward').textContent=`+${reward}`;ui.win.classList.add('show');beep(520,.15);setTimeout(()=>beep(660,.15),140);setTimeout(()=>beep(790,.2),280)}
function startLevel(i=current){current=Math.max(0,Math.min(i,LEVELS.length-1));build();paused=false;ui.start.classList.remove('show');ui.pause.classList.remove('show');ui.win.classList.remove('show');last=performance.now();toast(`Nivel ${current+1}: ${LEVELS[current].t}`)}
function init(){try{ui.loadingText.textContent='Compilando shaders WebGL';initGL();ui.loadingText.textContent='Construyendo cubos tridimensionales';build();bind();save.sound=save.sound!==false;save.vibration=save.vibration!==false;$('#sound').checked=save.sound;$('#vibration').checked=save.vibration;$('#quality').value=save.quality;requestAnimationFrame(loop);setTimeout(()=>ui.loading.classList.add('hide'),320);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}catch(err){console.error(err);ui.loading.classList.add('hide');ui.errorText.textContent=err.message||String(err);ui.error.classList.add('show')}}
function bind(){ui.canvas.addEventListener('pointerdown',pointerDown,{passive:false});ui.canvas.addEventListener('pointermove',pointerMove,{passive:false});ui.canvas.addEventListener('pointerup',pointerUp,{passive:false});ui.canvas.addEventListener('pointercancel',pointerUp,{passive:false});$('#play').onclick=()=>startLevel(save.level||0);$('#pause').onclick=()=>{if(!paused){paused=true;ui.pause.classList.add('show')}};$('#resume').onclick=()=>{paused=false;ui.pause.classList.remove('show');last=performance.now()};$('#restart').onclick=()=>startLevel(current);$('#replay').onclick=()=>startLevel(current);$('#next').onclick=()=>startLevel((current+1)%LEVELS.length);$('#hint').onclick=hint;$('#left').onclick=()=>targetYaw-=Math.PI/6;$('#right').onclick=()=>targetYaw+=Math.PI/6;$('#center').onclick=()=>targetYaw=0;$('#home').onclick=()=>{paused=true;ui.start.classList.add('show')};$('#settings').onclick=()=>{paused=true;ui.settings.classList.add('show')};$('#closeSettings').onclick=()=>{ui.settings.classList.remove('show');if(!ui.start.classList.contains('show')&&!ui.win.classList.contains('show')){paused=false;last=performance.now()}};$('#sound').onchange=e=>{save.sound=e.target.checked;persist()};$('#vibration').onchange=e=>{save.vibration=e.target.checked;persist()};$('#quality').onchange=e=>{save.quality=e.target.value;persist();resize();toast('Calidad aplicada')};$('#reset').onclick=()=>{if(confirm('¿Restablecer todo el progreso?')){localStorage.removeItem('wq3-native');location.reload()}};$('#retry').onclick=()=>location.reload();document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused){paused=true;ui.pause.classList.add('show')}})}
init();
